name: My First CI Pipeline

on:
  push:

jobs:
  check:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Check HTML File
      run: Test-Path index.html

    - name: Check CSS File
      run: Test-Path style.css

    - name: Check JavaScript File
      run: Test-Path script.js

